name: Setup Environment

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.18.0'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Generate GraphQL types
      run: npm run generate-types

    - name: Run database migrations
      run: npm run migrations:run
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db

    - name: Verify setup
      run: |
        echo "✅ Environment setup completed"
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "Available scripts:"
        npm run
